### ISSUE TITLE
no module name nvidia ...? 

### ISSUE THREAD

**Issue by JarveeLee** [tanglang96/DataLoaders_DALI#1]
Thanks for your great work. When I run this code , 
import nvidia.dali
raise error: " no module named 'nvidia' "
how can I fix this.

**Comment by tanglang96** [comment]
you should first install naidia-dali like this
```
#for cuda9.0
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/9.0 nvidia-dali
#for cuda10.0
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali
```

**Comment by JarveeLee** [comment]
I have installed naidia-dali but still encounter this error ...

**Comment by tanglang96** [comment]
maybe you can try `pip3 install`, details about how to install DALI can be found [here](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/index.html)
