### ISSUE TITLE
你好，这个代码在imagenet上训练过吗？为什么每个epoch gpu内存都会增长，最后OOM

### ISSUE THREAD

**Issue by betterhalfwzm** [tanglang96/DataLoaders_DALI#10]
你好，这个代码在imagenet上训练过吗？为什么每个epoch gpu内存都会增长，最后OOM

**Comment by tanglang96** [comment]
有训练过，尝试把batch size调小一点试试？我这里是显存比较稳定，内存会缓慢增长

**Comment by betterhalfwzm** [comment]
@tanglang96 你的参数能给我看一下吗？我设的batch_size=128

**Comment by tanglang96** [comment]
我的V100显存是32g，batchsize可以开到256，建议从32开始慢慢往上加

**Comment by betterhalfwzm** [comment]
@tanglang96 我的gpu 2080ti 12g，你到最后显存占多少啊？

**Comment by tanglang96** [comment]
占了大概一半左右，不过我模型也比较小，你可以先用32跑几个epoch看看，然后再往上加

**Comment by betterhalfwzm** [comment]
@tanglang96 好的，我再试试，谢谢了。我用的mobilenet v2，也不大，还是显存太小 。4个gpu训练的，dataloader只在第一个gpu上跑，对吧

**Comment by tanglang96** [comment]
4卡可以用[apex](https://github.com/NVIDIA/apex)的分布式来跑，参数就按照一张卡的配置来设置，相当于会把batch_size乘4，这部分我会在后面补上

**Comment by betterhalfwzm** [comment]
@tanglang96 我看这个分布式了，还没时间尝试，期待你的代码，我先这么跑着，任务比较急。谢谢了

**Comment by winycg** [comment]
内存逐渐上涨是NVIDIA-DALI的Bug，我之前跑DALI仓库里的demo时也出现了以epoch为单位内存上涨
