### ISSUE TITLE
Shift from 'async' to 'non_blocking' in cuda

### ISSUE THREAD

**Issue by jduan1** [tanglang96/DataLoaders_DALI#2]
`async` has become a python keyword in python 3.7. The `cuda` method should accept `non_blocking` as its argument.

refs.
[https://github.com/pytorch/pytorch/blob/4d28b65fb8978f1c34765d56f18c07042e70a43a/torch/_utils.py#L20-L21](url)
[https://www.python.org/dev/peps/pep-0492/#deprecation-plans](url)

**Comment by tanglang96** [comment]
thanks for your correction, I've fixed this
