### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by GA-17a** [tanglang96/DataLoaders_DALI#25]
运行时，在函数DALIDataloader(pipeline=pip_train, size=IMAGENET_IMAGES_NUM_TRAIN, batch_size=TRAIN_BS, onehot_label=True)中报出错误：AttributeError: can't set attribute。是dali的DALIGenericIterator中加了什么限制吗？求指导 @tanglang96 ，谢谢

**Comment by WangWenhao0716** [comment]
+1

**Comment by WangWenhao0716** [comment]
Rename it as "self.size_1" can solve this problem.

**Comment by GA-17a** [comment]
I also solved it.
