### ISSUE TITLE
How does the imagenet dir  organized?

### ISSUE THREAD

**Issue by henanjun** [tanglang96/DataLoaders_DALI#4]
I want to run 'imagenet.py' and it needs specify a 'path' to 'image_dir'. Can you show me how does the files organized in 'image_dir'? Thank you very much,

**Comment by tanglang96** [comment]
It's similar to `torchvision.datasets.ImageFolder`, images are arranged in this way:
```
path/dog/xxx.png
path/dog/xxy.png
path/dog/xxz.png

path/cat/123.png
path/cat/nsdf3.png
path/cat/asd932_.png
```

**Comment by henanjun** [comment]
Thanks for kind reply.:)
