### ISSUE TITLE
imagenet大约快多少啊

### ISSUE THREAD

**Issue by betterhalfwzm** [tanglang96/DataLoaders_DALI#7]
你好，读取imagenet速度有多大的提升，谢谢

**Comment by tanglang96** [comment]
这个跟你的硬件环境有关，我把imagenet加载进内存，8线程的cpu大概20倍左右，可以考虑拿Imagenet的脚本在你的环境测试一下

**Comment by betterhalfwzm** [comment]
这个很占gpu内存啊，多gpu试过吗

**Comment by betterhalfwzm** [comment]
这个很占gpu内存啊，多gpu试过吗 @tanglang96

**Comment by betterhalfwzm** [comment]
@tanglang96 能指定gpu跑这个然后另一个gpu跑训练吗？
