### ISSUE TITLE
请问在使用 FileReader 读 image 的时候，可以获取读取的 image 的路径吗

### ISSUE THREAD

**Issue by kgl-prml** [tanglang96/DataLoaders_DALI#9]

**Comment by tanglang96** [comment]
没太懂什么意思，读取的时候就是输入路径进行读取的呀

**Comment by gjd2017** [comment]
> 没太懂什么意思，读取的时候就是输入路径进行读取的呀

那label怎么读取呀？ 可以实现读取 train_list.txt文件么（xx.jpg + label的格式）

**Comment by tanglang96** [comment]
> > 没太懂什么意思，读取的时候就是输入路径进行读取的呀
> 
> 那label怎么读取呀？ 可以实现读取 train_list.txt文件么（xx.jpg + label的格式）

跟Imagefolder是一样的，文件夹反映了里面文件的类别
